### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Koreysherwin** [geoffsharris/Indigo-Rainmachine#1]
Indigo Server version 7.4.1 (Mac OS X 10.14.6)

` Starting plugin "RainMachineDev 0.1" (pid 31700)
   RainMachineDev Error            Error in plugin execution InitializeMain:

Traceback (most recent call last):
  File "plugin.py", line 18, in <module>
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RainMachineDev.indigoPlugin/Contents/Server Plugin/client.py", line 6, in <module>
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/RainMachineDev.indigoPlugin/Contents/Server Plugin/controller.py", line 8, in <module>
ImportError: No module named urllib3

   Stopping plugin "RainMachineDev 0.1" (pid 31700)
   Stopped plugin "RainMachineDev 0.1"
`

**Comment by geoffsharris** [comment]
Set new reference to urllib3 that should get around this not being installed by indigo. Let me know if this is resolved for you.

**Comment by Koreysherwin** [comment]
That fixes crash.
